name: Terraform

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  terraform-actions:
    name: Workflow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@master

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.10

    - name: Terraform Fmt
      id: fmt
      run: terraform fmt -check -diff
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      continue-on-error: true

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      continue-on-error: true
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: false
      env:
        TF_VAR_snowflake_account : ${{ secrets.SNOWFLAKE_ACCOUNT }}
        TF_VAR_snowflake_region : ${{ secrets.SNOWFLAKE_REGION }}
        TF_VAR_sf_tf_user_name : ${{ secrets.SF_TF_USER_NAME }}
        TF_VAR_sf_tf_user_password : ${{ secrets.SF_TF_USER_PASSWORD }}
        TF_VAR_sf_dbt_user_password : ${{ secrets.SF_DBT_USER_PASSWORD }}

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      continue-on-error: false
      env:
        TF_VAR_snowflake_account : ${{ secrets.SNOWFLAKE_ACCOUNT }}
        TF_VAR_snowflake_region : ${{ secrets.SNOWFLAKE_REGION }}
        TF_VAR_sf_tf_user_name : ${{ secrets.SF_TF_USER_NAME }}
        TF_VAR_sf_tf_user_password : ${{ secrets.SF_TF_USER_PASSWORD }}
        TF_VAR_sf_dbt_user_password : ${{ secrets.SF_DBT_USER_PASSWORD }}
